'StandardWrapper.Throwable' error not resolved
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'favourites': Injection of autowired dependencies
failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Could not
autowire field: UtilsService.DatabaseConnection
Controller.Favourites.dbConnection; nested exception is
org.springframework.beans.factory.NoSuchBeanDefinitionException: No
qualifying bean of type [UtilsService.DatabaseConnection] found for
dependency: expected at least 1 bean which qualifies as autowire
candidate for this dependency. Dependency annotations:
{@org.springframework.beans.factory.annotation.Autowired(required=true)}